import test from 'node:test'
import assert from 'node:assert/strict'

import type { MockDb } from '@/lib/mockdb/store'

import { syncSessionPointDerivedData } from './pipeline'

test('syncSessionPointDerivedData keeps point analysis but clears downstream trend when a shot is deleted', () => {
  const db: MockDb = {
    customers: [
      {
        id: 'customer-1',
        name: 'Amy',
        phone: null,
        notes: null,
        created_at: '2026-03-18T10:00:00.000Z',
        updated_at: '2026-03-18T10:00:00.000Z',
      },
    ],
    sessions: [
      {
        id: 'session-1',
        customer_id: 'customer-1',
        check_date: '2026-03-10T10:00:00.000Z',
        staff_name: null,
        notes: null,
        created_at: '2026-03-18T10:00:00.000Z',
        updated_at: '2026-03-18T10:00:00.000Z',
      },
      {
        id: 'session-2',
        customer_id: 'customer-1',
        check_date: '2026-03-11T10:00:00.000Z',
        staff_name: null,
        notes: null,
        created_at: '2026-03-18T10:00:00.000Z',
        updated_at: '2026-03-18T10:00:00.000Z',
      },
      {
        id: 'session-3',
        customer_id: 'customer-1',
        check_date: '2026-03-12T10:00:00.000Z',
        staff_name: null,
        notes: null,
        created_at: '2026-03-18T10:00:00.000Z',
        updated_at: '2026-03-18T10:00:00.000Z',
      },
    ],
    images: [
      {
        id: 'image-2-1',
        customer_id: 'customer-1',
        session_id: 'session-2',
        capture_point_code: 'front',
        shot_index: 1,
        image_type: 'micro',
        magnification: null,
        lighting_mode: null,
        hair_state: null,
        image_url: '/a.jpg',
        created_at: '2026-03-18T10:00:00.000Z',
        updated_at: '2026-03-18T10:00:00.000Z',
      },
      {
        id: 'image-2-2',
        customer_id: 'customer-1',
        session_id: 'session-2',
        capture_point_code: 'front',
        shot_index: 2,
        image_type: 'micro',
        magnification: null,
        lighting_mode: null,
        hair_state: null,
        image_url: '/b.jpg',
        created_at: '2026-03-18T10:00:00.000Z',
        updated_at: '2026-03-18T10:00:00.000Z',
      },
      {
        id: 'image-3-1',
        customer_id: 'customer-1',
        session_id: 'session-3',
        capture_point_code: 'front',
        shot_index: 1,
        image_type: 'micro',
        magnification: null,
        lighting_mode: null,
        hair_state: null,
        image_url: '/c.jpg',
        created_at: '2026-03-18T10:00:00.000Z',
        updated_at: '2026-03-18T10:00:00.000Z',
      },
      {
        id: 'image-3-2',
        customer_id: 'customer-1',
        session_id: 'session-3',
        capture_point_code: 'front',
        shot_index: 2,
        image_type: 'micro',
        magnification: null,
        lighting_mode: null,
        hair_state: null,
        image_url: '/d.jpg',
        created_at: '2026-03-18T10:00:00.000Z',
        updated_at: '2026-03-18T10:00:00.000Z',
      },
      {
        id: 'image-3-3',
        customer_id: 'customer-1',
        session_id: 'session-3',
        capture_point_code: 'front',
        shot_index: 3,
        image_type: 'micro',
        magnification: null,
        lighting_mode: null,
        hair_state: null,
        image_url: '/e.jpg',
        created_at: '2026-03-18T10:00:00.000Z',
        updated_at: '2026-03-18T10:00:00.000Z',
      },
    ],
    metrics: [
      {
        id: 'metric-2-1',
        image_id: 'image-2-1',
        oil_score: 1,
        redness_score: 1,
        density_score: 7,
        blockage_score: 1,
        dandruff_score: 1,
        sensitivity_score: 1,
        created_at: '2026-03-18T10:00:00.000Z',
        updated_at: '2026-03-18T10:00:00.000Z',
      },
      {
        id: 'metric-2-2',
        image_id: 'image-2-2',
        oil_score: 1,
        redness_score: 1,
        density_score: 7,
        blockage_score: 1,
        dandruff_score: 1,
        sensitivity_score: 1,
        created_at: '2026-03-18T10:00:00.000Z',
        updated_at: '2026-03-18T10:00:00.000Z',
      },
      {
        id: 'metric-3-1',
        image_id: 'image-3-1',
        oil_score: 1,
        redness_score: 1,
        density_score: 8,
        blockage_score: 1,
        dandruff_score: 1,
        sensitivity_score: 1,
        created_at: '2026-03-18T10:00:00.000Z',
        updated_at: '2026-03-18T10:00:00.000Z',
      },
      {
        id: 'metric-3-2',
        image_id: 'image-3-2',
        oil_score: 1,
        redness_score: 1,
        density_score: 8,
        blockage_score: 1,
        dandruff_score: 1,
        sensitivity_score: 1,
        created_at: '2026-03-18T10:00:00.000Z',
        updated_at: '2026-03-18T10:00:00.000Z',
      },
      {
        id: 'metric-3-3',
        image_id: 'image-3-3',
        oil_score: 1,
        redness_score: 1,
        density_score: 8,
        blockage_score: 1,
        dandruff_score: 1,
        sensitivity_score: 1,
        created_at: '2026-03-18T10:00:00.000Z',
        updated_at: '2026-03-18T10:00:00.000Z',
      },
    ],
    pointSummaries: [
      {
        id: 'summary-2',
        customer_id: 'customer-1',
        session_id: 'session-2',
        capture_point_code: 'front',
        oil_avg: 1,
        redness_avg: 1,
        density_avg: 7,
        blockage_avg: 1,
        dandruff_avg: 1,
        sensitivity_avg: 1,
        completed: true,
        computed_at: '2026-03-18T10:00:00.000Z',
      },
      {
        id: 'summary-3',
        customer_id: 'customer-1',
        session_id: 'session-3',
        capture_point_code: 'front',
        oil_avg: 1,
        redness_avg: 1,
        density_avg: 8,
        blockage_avg: 1,
        dandruff_avg: 1,
        sensitivity_avg: 1,
        completed: true,
        computed_at: '2026-03-18T10:00:00.000Z',
      },
    ],
    comparisons: [
      {
        id: 'comparison-3',
        customer_id: 'customer-1',
        capture_point_code: 'front',
        current_session_id: 'session-3',
        previous_session_id: 'session-2',
        oil_change: 0,
        redness_change: 0,
        density_change: 1,
        blockage_change: 0,
        dandruff_change: 0,
        sensitivity_change: 0,
        comparison_summary: 'existing',
        created_at: '2026-03-18T10:00:00.000Z',
      },
    ],
    aiShotAnalyses: [
      {
        id: 'ai-2-1',
        customer_id: 'customer-1',
        session_id: 'session-2',
        image_id: 'image-2-1',
        capture_point_code: 'front',
        shot_index: 1,
        hair_count_estimate: 80,
        confidence_score: 0.7,
        provider_name: 'heuristic',
        analysis_method: 'baseline-density-v1',
        model_version: 'heuristic-2026-03-18',
        status: 'ready',
        notes: null,
        fallback_used: false,
        fallback_reason: null,
        raw_output_ref: null,
        created_at: '2026-03-18T10:00:00.000Z',
        updated_at: '2026-03-18T10:00:00.000Z',
      },
      {
        id: 'ai-2-2',
        customer_id: 'customer-1',
        session_id: 'session-2',
        image_id: 'image-2-2',
        capture_point_code: 'front',
        shot_index: 2,
        hair_count_estimate: 82,
        confidence_score: 0.72,
        provider_name: 'heuristic',
        analysis_method: 'baseline-density-v1',
        model_version: 'heuristic-2026-03-18',
        status: 'ready',
        notes: null,
        fallback_used: false,
        fallback_reason: null,
        raw_output_ref: null,
        created_at: '2026-03-18T10:00:00.000Z',
        updated_at: '2026-03-18T10:00:00.000Z',
      },
      {
        id: 'ai-3-1',
        customer_id: 'customer-1',
        session_id: 'session-3',
        image_id: 'image-3-1',
        capture_point_code: 'front',
        shot_index: 1,
        hair_count_estimate: 90,
        confidence_score: 0.75,
        provider_name: 'heuristic',
        analysis_method: 'baseline-density-v1',
        model_version: 'heuristic-2026-03-18',
        status: 'ready',
        notes: null,
        fallback_used: false,
        fallback_reason: null,
        raw_output_ref: null,
        created_at: '2026-03-18T10:00:00.000Z',
        updated_at: '2026-03-18T10:00:00.000Z',
      },
      {
        id: 'ai-3-2',
        customer_id: 'customer-1',
        session_id: 'session-3',
        image_id: 'image-3-2',
        capture_point_code: 'front',
        shot_index: 2,
        hair_count_estimate: 91,
        confidence_score: 0.75,
        provider_name: 'heuristic',
        analysis_method: 'baseline-density-v1',
        model_version: 'heuristic-2026-03-18',
        status: 'ready',
        notes: null,
        fallback_used: false,
        fallback_reason: null,
        raw_output_ref: null,
        created_at: '2026-03-18T10:00:00.000Z',
        updated_at: '2026-03-18T10:00:00.000Z',
      },
      {
        id: 'ai-3-3',
        customer_id: 'customer-1',
        session_id: 'session-3',
        image_id: 'image-3-3',
        capture_point_code: 'front',
        shot_index: 3,
        hair_count_estimate: 92,
        confidence_score: 0.75,
        provider_name: 'heuristic',
        analysis_method: 'baseline-density-v1',
        model_version: 'heuristic-2026-03-18',
        status: 'ready',
        notes: null,
        fallback_used: false,
        fallback_reason: null,
        raw_output_ref: null,
        created_at: '2026-03-18T10:00:00.000Z',
        updated_at: '2026-03-18T10:00:00.000Z',
      },
    ],
    aiPointAnalyses: [
      {
        id: 'point-1',
        customer_id: 'customer-1',
        session_id: 'session-1',
        capture_point_code: 'front',
        hair_count_avg_3shot: 75,
        hair_count_min: 74,
        hair_count_max: 76,
        completed: true,
        provider_name: 'heuristic',
        analysis_method: 'baseline-density-v1',
        confidence_score: 0.7,
        capture_consistency_score: 0.92,
        change_vs_previous: null,
        fallback_used: false,
        trend_direction: 'inconclusive',
        trend_summary: 'No previous AI baseline is available for trend comparison yet.',
        computed_at: '2026-03-18T10:00:00.000Z',
      },
      {
        id: 'point-2',
        customer_id: 'customer-1',
        session_id: 'session-2',
        capture_point_code: 'front',
        hair_count_avg_3shot: 81,
        hair_count_min: 80,
        hair_count_max: 82,
        completed: true,
        provider_name: 'heuristic',
        analysis_method: 'baseline-density-v1',
        confidence_score: 0.71,
        capture_consistency_score: 0.95,
        change_vs_previous: 6,
        fallback_used: false,
        trend_direction: 'improved',
        trend_summary: 'Hair count trend is improving beyond the expected capture variance.',
        computed_at: '2026-03-18T10:00:00.000Z',
      },
      {
        id: 'point-3',
        customer_id: 'customer-1',
        session_id: 'session-3',
        capture_point_code: 'front',
        hair_count_avg_3shot: 91,
        hair_count_min: 90,
        hair_count_max: 92,
        completed: true,
        provider_name: 'heuristic',
        analysis_method: 'baseline-density-v1',
        confidence_score: 0.75,
        capture_consistency_score: 0.96,
        change_vs_previous: 10,
        fallback_used: false,
        trend_direction: 'improved',
        trend_summary: 'Hair count trend is improving beyond the expected capture variance.',
        computed_at: '2026-03-18T10:00:00.000Z',
      },
    ],
  }

  const affectedSessionIds = syncSessionPointDerivedData({
    db,
    customerId: 'customer-1',
    sessionId: 'session-2',
    capturePointCode: 'front',
    nowISO: '2026-03-18T10:00:00.000Z',
  })

  assert.deepEqual(affectedSessionIds, ['session-2', 'session-3'])

  const current = db.aiPointAnalyses.find((item) => item.session_id === 'session-2' && item.capture_point_code === 'front')
  const next = db.aiPointAnalyses.find((item) => item.session_id === 'session-3' && item.capture_point_code === 'front')

  assert.ok(current)
  assert.equal(current.completed, false)
  assert.equal(current.hair_count_avg_3shot, null)
  assert.equal(current.trend_direction, 'inconclusive')

  assert.ok(next)
  assert.equal(next.change_vs_previous, null)
  assert.equal(next.trend_direction, 'inconclusive')

  assert.equal(
    db.pointSummaries.some((item) => item.session_id === 'session-2' && item.capture_point_code === 'front'),
    false,
  )
  assert.equal(
    db.comparisons.some(
      (item) =>
        item.current_session_id === 'session-3' &&
        item.previous_session_id === 'session-2' &&
        item.capture_point_code === 'front',
    ),
    false,
  )
})
